### ISSUE TITLE
[Bug] .GetCredential() option throws error when secret has multiple password fields (0.34)

### ISSUE THREAD

**Issue by PatrickV-code** [thycotic-ps/thycotic.secretserver#133]
**Describe the bug**
after storing secret in variable and trying to build a pscredential object using the $secret.getcredential() option an error is thrown.
This is depending the template being used. In the case of a standard Active Directory template the error is not thrown and the pscredential object get created.
When using a template with multiple password fields (such as Unix account) the passwd value created is not a string but an object and thus can't be converted using convertto-securestring.

**To Reproduce**
1. PowerShell script:

```powershell
import-module Thycotic.SecretServer

$session = new-TssSession -SecretServer https://lab-sspm.lab.petje.com/secretserver/ -UseSdkClient -ConfigPath H:\sdk-powershell\

$secret = Get-TssSecret -TssSession $session -id 78

$username = $secret.GetFieldValue('username')
$password = $secret.GetFieldValue('password')

Write-Host "The username is $username"
Write-Host "The password is $password"

$cred = $secret.GetCredential()
```

1. Error/issue observed:

```powershell
$error | select *



PSMessageDetails      :
Exception             : System.Management.Automation.ParameterBindingException: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'String'. Specified method is not supported. --->
                        System.NotSupportedException: Specified method is not supported.
                           at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo,   
                        Object currentValue)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine,
                        ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                           at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
                           at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe,  
                        InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
                           at System.Management.Automation.ScriptBlock.InvokeAsMemberFunctionT[T](Object instance, Object[] args)
                           at CallSite.Target(Closure , CallSite , Object )
                           at System.Management.Automation.Interpreter.DynamicInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : InvalidArgument: (:) [ConvertTo-SecureString], ParameterBindingException
FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.ConvertToSecureStringCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at GetCredential, C:\Program Files\WindowsPowerShell\Modules\Thycotic.SecretServer\0.34.0\classes\secrets\TssSecret.class.ps1: line 129
                        at <ScriptBlock>, C:\Users\patrick.LAB\Github\Personal\SecretServer\Scripting\PowerShell\get-password - pwsh module.ps1: line 13
PipelineIterationInfo : {}
```

**Expected behavior**
storing of username password in a pscredential object.

**Environment (please complete the following information):**

***Secret Server***
Build/Version: 10.9.63

***PowerShell version***

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

***Host information:***

[x ] Powershell.exe
[ ] pwsh.exe
[ ] PowerShell ISE
[x ] VS Code (Insiders/Stable)

**Additional context**
Managed to track this down to the following component: TssSecret.class.ps1
Line 124 - 129

    [System.Management.Automation.PSCredential]
    GetCredential() {
        $username = ($this.Items | Where-Object FieldName -EQ 'username').ItemValue
        $passwd = ($this.Items | Where-Object IsPassword).ItemValue
        return [pscredential]::new($username,(ConvertTo-SecureString -AsPlainText -Force -String $passwd))

after running into the error and manually running the code above I checked the contents of $passwd
$passwd = ($secret.Items | Where-Object IsPassword).ItemValue
$passwd.GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array

contents actually translate back to the following:
($secret.Items | Where-Object IsPassword)          

ItemId FieldId FieldName              ItemValue    Slug                   Filename
------ ------- ---------              ---------    ----                   --------
332    110     Password               redacted       password
335    190     Private Key Passphrase              private-key-passphrase

so we would or need to validate that there are not more secret fields and throw a more friendly error (can't create credentials as secret has more password fields).. or do further error handling to try and filter out the actual password we want.

**Comment by wsmelton** [comment]
> storing of username password in a pscredential object.

This is actually broken in more ways for AD secrets that I did not catch prior. A proper PSCredential for the 6001 template would be having the Username created as `domain\username` slugs, and then the `password` slug pulled. 

With Unix, I'd have to be told which slug you wanted to use for a password value. It can vary even more with custom templates based on how they created and if they keep with the standard slug names of `username` and `password`. 

Only clean way I'd see this being fixed for all use cases would be to require the slug names being provided:

```powershell
[pscredential] GetCredential([string] slug, [string] slug, [string], slug)
```

This would be a breaking change but is required to address both Unix based templates and the AD template too. This would allow you to create a `PSCredential` on any combination that you want:

```powershell
$secret.GetCredential('domain','username','password')
```

**Comment by wsmelton** [comment]
@PatrickV-code fixe can be found in v0.35.0 branch and will be included when I get the next release out.
