### ISSUE TITLE
Cannot pull secret using Thycotic version 1.5.0

### ISSUE THREAD

**Issue by tieulong042** [thycotic-ps/thycotic.secretserver#403]
### Verified issue does not already exist?

Yes

### What error did you receive

Thycotic.SecretServer.Sdk.Infrastructure.Exceptions.SecretServerHttpException: Reason: Bad Request - 400 Content: {"error":"invalid_client"}
   at Thycotic.SecretServer.Sdk.Extensions.Integration.Clients.SecretServerClient.GetSecret(Int32 id)
   at Test.ServiceSetup.BuildConnectionString(PAMConfig config) in D:\src\Test\ServiceSetup.cs:line 96
   at Test.<>c__DisplayClass5_0.<AddDatabases>b__0(DbContextOptionsBuilder options) in D:\src\Test\ServiceSetup.cs:line 73
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass1_0`2.<AddDbContext>b__0(IServiceProvider _, DbContextOptionsBuilder b)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c__DisplayClass17_0`1.<AddCoreServices>b__0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)

### Provide a test case or steps to reproduce

I am using Thycotic version 1.5.0 to pull secret from Dealine server, using in my .NET core project.
I noticed that from last week, the pulling secret was not working event if it was working fine before, the got the error above. Once removed the nuget packages and added these back, it turn back working. Not sure what is issue in this case?

### Expected behavior

Able to pull secret from server

### What Edition of Secret Server?

Platinum

### What version of Secret Server

Secret Server Cloud

### What PowerShell host was used when producing this error

VS Code (terminal)

### PowerShell Host Version

N/A

**Comment by jagger** [comment]
PR #435 (merged today) updates the bundled Secret Server SDK CLI from 1.0.0.0 to 1.6.1. The original report referenced "Thycotic version 1.5.0" which we now believe refers to the SDK CLI rather than the module. Can you confirm whether this issue is still reproducible with module 0.62.0 once it ships? Closing this in ~14 days if no response.
